### ISSUE TITLE
Issue with checkHTTPChallenge

### ISSUE THREAD

**Issue by yellow1912** [Zwartpet/php-certificate-toolbox#10]
## Detailed description

I'm not sure if this is an issue of this specific library, or due to a combination of modules being used.

The following method:

`public function checkHTTPChallenge($domain, $token, $keyAuthorization)`

Will throw an exception "host is empty" when called.

## Context + environment

I run this library with [Swoole](https://github.com/swoole/swoole-src), Guzzle 7, and [Swoole Guzzle](https://github.com/Yurunsoft/Guzzle-Swoole). The combination of these libraries may be the cause of the issue. In any case, I think adding (or allow specifying) the host to prepend to the domain should make sense in this case.

## Possible implementation

If I simply add something like:

`$requestURL = 'http://' . $domain . '/.well-known/acme-challenge/' . $token;`

Then the error will be resolved.

**Comment by Zwartpet** [comment]
You might have to setup the guzzle client with a base uri: new Client(['base_uri' => $domain]).
Let me know if this solves the issue.

**Comment by Zwartpet** [comment]
Ah never mind, didn't read it correctly

**Comment by Zwartpet** [comment]
Created new release with fix: [2.0.1](https://github.com/Zwartpet/php-certificate-toolbox/releases/tag/2.0.1)
