### ISSUE TITLE
Issue with renewing expired certificate

### ISSUE THREAD

**Issue by yellow1912** [Zwartpet/php-certificate-toolbox#13]
## Detailed description

There is no clear instruction on renewing the existing cert, so in this case, I assume that I only have to re-run the code that generated the cert in the first place. Please let me know if that's not recommended.

That said, My code looks somewhat like this:

```
logger = new DiagnosticLogger();
$client = new LEClient(
    ['support@email.org'],
    LEClient::LE_PRODUCTION,
    $logger,
    new Client()
);

// Get or create order. The basename is preferably the top domain name.
// This will be the directory in which the keys are stored.
// Supply an array of string domain names to create a certificate for.
$order = $client->getOrCreateOrder($domains[0], $domains);
```

I ran into this error:

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://acme-v02.api.letsencrypt.org/acme/order/118899777/9015219154` resulted in a `404 Not Found` response:
{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "No order for ID 9015219154",
  "status": 404
}

```

I'm not exactly sure yet why it happens. My guess is this: since the code attempts to load the order id for the existing cert, which is stored locally on file, and since a long time has passed already, this order id is no longer valid. 

Either I'm doing something wrong (perhaps I should not use the getOrCreateOrder in this case? Or perhaps there must be a way to force regeneration for new order?

**Comment by Zwartpet** [comment]
After the certificate is issued the directory should be cleaned up, letsencrypt deletes the order from its database after a while.

Renewing a certificate at letsencrypt is just ordering a new one.

**Comment by yellow1912** [comment]
Thank you for your very quick response. Is there a method to call to remove the folder, or should I remove that myself? Also, I see 2 folders: account and certificates, should I remove both?

**Comment by Zwartpet** [comment]
There’s currently no method to remove the folder, only the certificates folder has to be removed, account can stay.

**Comment by Zwartpet** [comment]
Closing this issue, if you have any troubles let me know 👍
